baseURL = 'https://www.listenings.nl/'
languageCode = 'en-us'
title = 'Listenings'
theme = 'ananke'
googleAnalytics = 'G-TLSDKGX71H'
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
    name = "Manifesto"
    url = "/manifesto/"
    weight = 10

[[menu.main]]
    name = "Archive"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "Authors"
    url = "/author/"
    weight = 30
    
[params]
    mainSections = ["posts"]
    text_summary_length = 200


[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  author = "author"


