baseURL = 'https://www.listenings.nl/'
languageCode = 'en-us'
title = 'Listenings'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
    name = "Manifesto"
    url = "/manifesto/"
    weight = 10

[[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 20

[params]
    mainSections = ["archive"]
    text_summary_length = 200

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  author = "author"
